In [1]:
import numpy as np
import torch

/home/yangfei/anaconda3/envs/d2/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [23]:
Rotations = np.load('./pose_exp/insert_mold_R.npz')
print(Rotations['Rotation'][4])
Quaternions = np.load('./pose_exp/insert_mold_Q.npz')
print(Quaternions['Quaternions'][4])
print(len(Quaternions['Quaternions']))

[[ 2.11488366e-01  8.92689824e-01  3.97966832e-01]
 [ 9.77380514e-01 -1.93065494e-01 -8.63313451e-02]
 [-2.33450482e-04  4.07223076e-01 -9.13328707e-01]]
[0.         0.         0.         0.76122968 0.61416099 0.130622
 0.16209116]
150
